






exe: main.cpp vecteurTransition.h vecteurTransition.cpp matriceMot.h matriceMot.cpp tensorMot.h tensorMot.cpp corpus.h corpus.cpp misc.h misc.cpp
	g++ -o main main.cpp vecteurTransition.cpp matriceMot.cpp tensorMot.cpp corpus.cpp  misc.cpp

