






exe: main2.cpp vecteurTransition.h vecteurTransition.cpp matriceMot.h matriceMot.cpp tensorMot.h tensorMot.cpp corpus.h corpus.cpp
	g++ -o main2 main2.cpp vecteurTransition.cpp matriceMot.cpp tensorMot.cpp corpus.cpp 

